language: node_js
sudo: false
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IeXJwcXfeaywDcFJ6hNTHncgnRQopLsZKQ8BmZAx2aM8Pyj2tAG4ICMMmU+/hPeSB6TdueV0gS18rphRnqacuWP2PrjX7bSoww8MjzVTdt5XeOXWUgcRCYdq+te+ahj/yyGdNYZe703dsL51ZMErmuyE7tpnqRhHlgDy2Rllzng=
  file:
    - "coleman-liau.js"
    - "coleman-liau.min.js"
  on:
    tags: true
